# Change baseurl before deploy
baseurl = "https://lighturway-astro.pages.dev"
languageCode = "zh-tw"
title = "命理小天地 官方網站"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage =true

[languages]
  [languages.zh-tw]
    languageName = "繁體中文"
    weight = 1
    contentDir = "content/zh-tw"

# Change it to your Disqus shortname before using
disqusShortname = "lighturway-astro"

[pagination]
pagerSize = 5

[params]
  adsense = true  # 控制廣告開關
  adsenseClient = "ca-pub-7855260357994149"